name: 'transform_data'
version: '1.0.0'
profile: 'dev'

## Configuring directories
source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

## Configuring models
models:
  transform_data:
    materialized: view